name: CI

on:
push:
workflow_dispatch:

Jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: Invoke-Webrequset https://bin.equinox.io/c/4VmDezA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Authenticate with ngrok
      run: ./ngrok/ngrok.exe authtoken sEnv:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: S{{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable Remote Desktop
      run:
        Set-ItemProperty -Patch 'HKLM:/System/CurrentControlset/Control/Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Patch 'HKLM:/System/CurrentControlset/Control/Terminal Server/WinStations/RDP-TOP' -name
"UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ss0rd!" -Force
    -name: Create ngrok tunnel to remote desktop
     run: ./ngrok/ngrok.exe tcp 3389
